### ISSUE TITLE
Failed to validate the SSL certificate for download.ceph.com:443

### ISSUE THREAD

**Issue by pezzaf** [red-hat-storage/RHCS-vagrant#2]
Hey Chris,

Thanks for your great work on the $Topic
I have tried to build up the demo for the RHS-C 2, however every things works well
until the Cluster creation from the dashboard.
- Package installation failed on: rhcs{1..6}
- from /var/log/skyring/skyring.log

TASK [ceph.ceph-common : install the ceph stable repository key] ***************
fatal: [rhcs1]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for download.ceph.com:443. Make sure your managed systems have a valid CA certificate installed. You c
an use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/t
ls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

That error is the same for all 6 nodes.
RH Network is available, the DNS ping works without loss packages.

Do you have any thoughts?
Can we try to switch with subscription-manager via Employee Subs?

Let me know. ^^
Cheers,
Fabrizio

**Comment by pezzaf** [comment]
$ curl -kL https://download.ceph.com
curl: (35) TCP connection reset by peer
$ date
mer 12 ott 2016, 22.56.54, CEST

**Comment by dang** [comment]
The data center containing ceph.com is experiencing an outage at the moment.  Try eu.ceph.com, maybe?

**Comment by mulbc** [comment]
I think this can now be closed - ceph.com was having an issue at that time... Additionally this was an error coming from ceph-ansible... so this probably did not only affect users of this repo
